// src/components/EducationItem.vue
<template>
  <div class="mb-3">
    <ul class="list-inline">
      <li class="list-inline-item"><h5>{{ item.degree }}</h5></li>
      <li class="list-inline-item float-end text-muted">{{ item.start }} - {{ item.end }}</li>
    </ul>
    {{ item.university }}, {{ item.faculty }}<br>
    <small>
      Специальность<br>
      <span class="text-muted">{{ item.specialization.code }} {{ item.specialization.name }}</span><br>
      Направление<br>
      <span class="text-muted">{{ item.program }}</span><br>
      Дипломная работа<br>
      <a :href="item.diploma.href" target="_blank">{{ item.diploma.title }}</a>
    </small>
  </div>
</template>

<script>
export default {
  name: 'EducationItem',
  props: ['item']
};
</script>

// src/components/EducationItem.tsx
import type { FC } from "react";

interface ISpecialization {
  i18: string;
  name: string;
}

interface IQualification {
  i18: string;
  code: string;
  name: string;
}

interface IDiploma {
  i18: string;
  title?: string;
  href?: string;
}

interface EducationItemProps {
  start: number;
  end: number;
  university: string;
  department: string;
  degree: string;
  specialization: ISpecialization;
  qualification: IQualification;
  diploma?: IDiploma;
}

const EducationItem: FC<EducationItemProps> = (props) => {
  return (
    <li className="py-2">
      <time className="text-xs opacity-50">{`${props.start}-${props.end}`}</time>
      <p className="text-lg font-medium">{`${props.university}, ${props.department}`}</p>
      <p className="text-sm">{props.degree}</p>
      <p className="font-medium">{props.qualification.i18}</p>
      <p className="text-sm">{`${props.qualification.code} ${props.qualification.name}`}</p>
      <p className="font-medium">{props.specialization.i18}</p>
      <p className="text-sm">{props.specialization.name}</p>
      <p className="font-medium">{props.diploma?.i18}</p>
      <a
        className="text-sm opacity-50 transition duration-300 hover:opacity-100"
        href={props.diploma?.href}
        target="_blank"
      >
        {props.diploma?.title ? `# ${props.diploma.title}` : ""}
      </a>
    </li>
  );
};

export default EducationItem;
