// src/components/ThemeSwitcher.tsx
import { type FC, useState, useEffect } from "react";

import SunIcon from "@components/icons/Sun";
import MoonIcon from "@components/icons/Moon";

const ThemeSwitcher: FC = () => {
  const [theme, setTheme] = useState(localStorage.getItem("theme") ?? "dark");
  const [isMounted, setIsMounted] = useState(false);

  useEffect(() => {
    setIsMounted(true);
  }, []);

  const onClick = () => {
    setTheme(theme === "light" ? "dark" : "light");
  };

  useEffect(() => {
    if (theme === "dark") {
      document.documentElement.classList.add("dark");
    } else {
      document.documentElement.classList.remove("dark");
    }
    localStorage.setItem("theme", theme);
  }, [theme]);

  if (!isMounted) return null;

  return (
    <button
      className="inline-block p-5 align-middle opacity-50 transition duration-300 hover:opacity-100"
      onClick={onClick}
    >
      {theme === "light" ? <SunIcon /> : <MoonIcon />}
    </button>
  );
};

export default ThemeSwitcher;

// src/components/ThemeSwitcher.vue
<template>
  <div class="text-center">
    <div class="d-inline-block"><i class="fas fa-sun mx-2"></i></div>
    <div class="d-inline-block"><MDBSwitch v-model="themeSwitcher" /></div>
    <div class="d-inline-block"><i class="fas fa-moon"></i></div>
  </div>
</template>

<script>
import { ref, watch, onMounted } from "vue";
import { MDBSwitch } from "mdb-vue-ui-kit";

export default {
  name: "ThemeSwitcher",
  components: {
    MDBSwitch,
  },
  setup() {
    const storageTheme = localStorage.getItem("isDarkTheme");
    const themeSwitcher = ref(
      storageTheme ? JSON.parse(storageTheme) : undefined
    );
    const setColorTheme = (isDarkTheme) => {
      if (isDarkTheme) {
        document.documentElement.classList.add("tw-dark");
      } else {
        document.documentElement.classList.remove("tw-dark");
      }
    };
    onMounted(() => setColorTheme(themeSwitcher.value));
    watch(
      () => themeSwitcher.value,
      (value) => {
        setColorTheme(value);
        localStorage.setItem("isDarkTheme", value);
      }
    );
    return {
      themeSwitcher,
    };
  },
};
</script>
